 # Python For Data Science

 Numpy Cheat Sheet 
 
 Notes from datacamp

 Sharing: Edgar Rios https://linktr.ee/erlinares

## Import Library

In [84]:
import numpy as np

## Creating Arrays

In [85]:
a = np.array([1,2,3]) #1D Array
a

array([1, 2, 3])

In [86]:
b = np.array([(1.5,2,3), (4,5,6)], dtype = float) #2D Array
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [87]:
c = np.array([[(1.5,2,3), (4,5,6)],[(3,2,1), (4,5,6)]], dtype = float) #3D Array
c

array([[[1.5, 2. , 3. ],
        [4. , 5. , 6. ]],

       [[3. , 2. , 1. ],
        [4. , 5. , 6. ]]])

### Initial Placeholders

In [88]:
np.zeros((3,4)) #Create an array of zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [89]:
np.ones((2,3,4),dtype=np.int16) #Create an array of ones

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [90]:
d = np.arange(10,25,5) #Create an array of evenly spaced values (step value)
d

array([10, 15, 20])

In [91]:
np.linspace(0,2,9) #Create an array of evenly spaced values (number of samples)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [92]:
e = np.full((2,2),7) #Create a constant array
e

array([[7, 7],
       [7, 7]])

In [93]:
f = np.eye(2) #Create a 2X2 identity matrix
f

array([[1., 0.],
       [0., 1.]])

In [94]:
np.random.random((2,2)) #Create an array with random values

array([[0.92019547, 0.53109566],
       [0.64589959, 0.88121478]])

In [95]:
np.empty((3,2)) #Create an empty array

array([[1.5, 2. ],
       [3. , 4. ],
       [5. , 6. ]])

## I/O

### Saving & Loading On Disk

In [96]:
np.save('my_array', a)

In [97]:
np.savez('array.npz', a, b)

In [98]:
np.load('my_array.npy')

array([1, 2, 3])

### Saving & Loading Text Files

In [99]:
np.savetxt("myfile.txt", a, delimiter=" ") 

In [100]:
np.loadtxt("myfile.txt")

array([1., 2., 3.])

In [101]:
np.genfromtxt("my_file.csv", delimiter=',')

## Asking For Help

In [152]:
np.info(np.ndarray.dtype)

Data-type of the array's elements.

Parameters
----------
None

Returns
-------
d : numpy dtype object

See Also
--------
numpy.dtype

Examples
--------
>>> x
array([[0, 1],
       [2, 3]])
>>> x.dtype
dtype('int32')
>>> type(x.dtype)
<type 'numpy.dtype'>


## Inspecting Your Array

In [102]:
a.shape # array dimensions

(3,)

In [103]:
len(a) # length of array

3

In [105]:
b.ndim #Number of array dimensions

2

In [104]:
e.size #Number of array elements

4

In [106]:
b.dtype #Data type of array elements

dtype('float64')

In [107]:
b.dtype.name #Name of data type

'float64'

In [108]:
b.astype(int) #Convert an array to a different type

array([[1, 2, 3],
       [4, 5, 6]])

## Data Types

In [109]:
 np.int64 #Signed 64-bit integer types

numpy.int64

In [110]:
np.float32 #Standard double-precision floating point

numpy.float32

In [111]:
np.complex128 #Complex numbers represented by 128 floats

numpy.complex128

In [112]:
np.bool_ #Boolean type storing TRUE and FALSE values Numpy

numpy.bool_

In [113]:
np.object #Python object type

<ipython-input-113-493a8c0fcc46>:1: DeprecationWarning: `np.object` is a deprecated alias for the builtin `object`. To silence this warning, use `object` by itself. Doing this will not modify any behavior and is safe. 
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  np.object #Python object type


object

In [114]:
np.string_ #Fixed-length string type

numpy.bytes_

In [115]:
np.unicode_ #Fixed-length unicode type

numpy.str_

## Array Mathematics

### Arithmetic Operations

In [116]:
g = a - b #Subtraction
g

array([[-0.5,  0. ,  0. ],
       [-3. , -3. , -3. ]])

In [117]:
np.subtract(a,b) #Subtraction

array([[-0.5,  0. ,  0. ],
       [-3. , -3. , -3. ]])

In [118]:
b + a #Addition

array([[2.5, 4. , 6. ],
       [5. , 7. , 9. ]])

In [119]:
np.add(b,a) #Addition

array([[2.5, 4. , 6. ],
       [5. , 7. , 9. ]])

In [120]:
a / b #Division

array([[0.66666667, 1.        , 1.        ],
       [0.25      , 0.4       , 0.5       ]])

In [121]:
np.divide(a,b) #Division

array([[0.66666667, 1.        , 1.        ],
       [0.25      , 0.4       , 0.5       ]])

In [122]:
a * b #Multiplication

array([[ 1.5,  4. ,  9. ],
       [ 4. , 10. , 18. ]])

In [123]:
np.multiply(a,b) #Multiplication

array([[ 1.5,  4. ,  9. ],
       [ 4. , 10. , 18. ]])

In [124]:
np.exp(b) #Exponentiation

array([[  4.48168907,   7.3890561 ,  20.08553692],
       [ 54.59815003, 148.4131591 , 403.42879349]])

In [125]:
np.sqrt(b) #Square root

array([[1.22474487, 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [126]:
np.sin(a) #Print sines of an array

array([0.84147098, 0.90929743, 0.14112001])

In [127]:
np.cos(b) #Element-wise cosine

array([[ 0.0707372 , -0.41614684, -0.9899925 ],
       [-0.65364362,  0.28366219,  0.96017029]])

In [128]:
np.log(a) #Element-wise natural logarithm

array([0.        , 0.69314718, 1.09861229])

In [129]:
e.dot(f) #Dot product

array([[7., 7.],
       [7., 7.]])

### Comparison

In [130]:
a == b #Element-wise comparison

array([[False,  True,  True],
       [False, False, False]])

In [131]:
a < 2 #Element-wise comparison

array([ True, False, False])

In [132]:
print(a)

[1 2 3]


In [133]:
print(b)

[[1.5 2.  3. ]
 [4.  5.  6. ]]


In [134]:
x = [2,1,1]
a < x

array([ True, False, False])

In [135]:
np.array_equal(a, b) #Array-wise comparison

False

### Aggregate Functions


In [136]:
a.sum() #Array-wise sum

6

In [137]:
a.min() #Array-wise minimum value

1

In [138]:
b.max(axis=0) #Maximum value of an array row

array([4., 5., 6.])

In [139]:
print(b)

[[1.5 2.  3. ]
 [4.  5.  6. ]]


In [140]:
b.cumsum(axis=1) #Cumulative sum of the elements

array([[ 1.5,  3.5,  6.5],
       [ 4. ,  9. , 15. ]])

In [141]:
a

array([1, 2, 3])

In [142]:
a.mean() #Mean

2.0

In [143]:
np.median(b) #Median

3.5

In [144]:
 y = np.array ([20,21,20,22,23,20,19])
 print ('Sum', y.sum())
 print ('Count', y.size)
 print ('Mean', y.mean())
 print ('Median', np.median(y))

Sum 145
Count 7
Mean 20.714285714285715
Median 20.0


In [145]:
np.corrcoef(a) #Correlation coefficient

1.0

In [146]:
np.std(b) #Standard deviation

1.5920810978785667

In [147]:
np.std(y) #Standard deviation

1.2777531299998799

## Copying Arrays

In [148]:
h = a.view() #Create a view of the array with the same data

In [149]:
h

array([1, 2, 3])

In [150]:
np.copy(a) #Create a copy of the array

array([1, 2, 3])

In [151]:
k = a.copy() #Create a deep copy of the array
k

array([1, 2, 3])