 # Python For Data Science

 Numpy Cheat Sheet 
 
 Notes from datacamp

 Sharing: Edgar Rios https://linktr.ee/erlinares

## Import Library

In [2]:
import numpy as np

## Creating Arrays

In [3]:
a = np.array([1,2,3]) #1D Array
a

array([1, 2, 3])

In [4]:
b = np.array([(1.5,2,3), (4,5,6)], dtype = float) #2D Array
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [5]:
c = np.array([[(1.5,2,3), (4,5,6)],[(3,2,1), (4,5,6)]], dtype = float) #3D Array
c

array([[[1.5, 2. , 3. ],
        [4. , 5. , 6. ]],

       [[3. , 2. , 1. ],
        [4. , 5. , 6. ]]])

### Initial Placeholders

In [6]:
np.zeros((3,4)) #Create an array of zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [7]:
np.ones((2,3,4),dtype=np.int16) #Create an array of ones

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [8]:
d = np.arange(10,25,5) #Create an array of evenly spaced values (step value)
d

array([10, 15, 20])

In [9]:
np.linspace(0,2,9) #Create an array of evenly spaced values (number of samples)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [10]:
e = np.full((2,2),7) #Create a constant array
e

array([[7, 7],
       [7, 7]])

In [11]:
f = np.eye(2) #Create a 2X2 identity matrix
f

array([[1., 0.],
       [0., 1.]])

In [12]:
np.random.random((2,2)) #Create an array with random values

array([[0.94975035, 0.45901469],
       [0.59887142, 0.59774854]])

In [13]:
np.empty((3,2)) #Create an empty array

array([[1.5, 2. ],
       [3. , 4. ],
       [5. , 6. ]])

## I/O

### Saving & Loading On Disk

In [14]:
np.save('my_array', a)

In [15]:
np.savez('array.npz', a, b)

In [16]:
np.load('my_array.npy')

array([1, 2, 3])

### Saving & Loading Text Files

In [17]:
np.savetxt("myfile.txt", a, delimiter=" ") 

In [18]:
np.loadtxt("myfile.txt")

array([1., 2., 3.])

In [19]:
np.genfromtxt("my_file.csv", delimiter=',')

OSError: ignored

## Asking For Help

In [20]:
np.info(np.ndarray.dtype)

Data-type of the array's elements.

Parameters
----------
None

Returns
-------
d : numpy dtype object

See Also
--------
numpy.dtype

Examples
--------
>>> x
array([[0, 1],
       [2, 3]])
>>> x.dtype
dtype('int32')
>>> type(x.dtype)
<type 'numpy.dtype'>


## Inspecting Your Array

In [21]:
a.shape # array dimensions

(3,)

In [22]:
len(a) # length of array

3

In [23]:
b.ndim #Number of array dimensions

2

In [24]:
e.size #Number of array elements

4

In [25]:
b.dtype #Data type of array elements

dtype('float64')

In [26]:
b.dtype.name #Name of data type

'float64'

In [27]:
b.astype(int) #Convert an array to a different type

array([[1, 2, 3],
       [4, 5, 6]])

## Data Types

In [28]:
 np.int64 #Signed 64-bit integer types

numpy.int64

In [29]:
np.float32 #Standard double-precision floating point

numpy.float32

In [30]:
np.complex128 #Complex numbers represented by 128 floats

numpy.complex128

In [31]:
np.bool_ #Boolean type storing TRUE and FALSE values Numpy

numpy.bool_

In [32]:
np.object #Python object type

<ipython-input-32-493a8c0fcc46>:1: DeprecationWarning: `np.object` is a deprecated alias for the builtin `object`. To silence this warning, use `object` by itself. Doing this will not modify any behavior and is safe. 
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  np.object #Python object type


object

In [33]:
np.string_ #Fixed-length string type

numpy.bytes_

In [34]:
np.unicode_ #Fixed-length unicode type

numpy.str_

## Array Mathematics

### Arithmetic Operations

In [35]:
g = a - b #Subtraction
g

array([[-0.5,  0. ,  0. ],
       [-3. , -3. , -3. ]])

In [36]:
np.subtract(a,b) #Subtraction

array([[-0.5,  0. ,  0. ],
       [-3. , -3. , -3. ]])

In [37]:
b + a #Addition

array([[2.5, 4. , 6. ],
       [5. , 7. , 9. ]])

In [38]:
np.add(b,a) #Addition

array([[2.5, 4. , 6. ],
       [5. , 7. , 9. ]])

In [39]:
a / b #Division

array([[0.66666667, 1.        , 1.        ],
       [0.25      , 0.4       , 0.5       ]])

In [40]:
np.divide(a,b) #Division

array([[0.66666667, 1.        , 1.        ],
       [0.25      , 0.4       , 0.5       ]])

In [41]:
a * b #Multiplication

array([[ 1.5,  4. ,  9. ],
       [ 4. , 10. , 18. ]])

In [42]:
np.multiply(a,b) #Multiplication

array([[ 1.5,  4. ,  9. ],
       [ 4. , 10. , 18. ]])

In [43]:
np.exp(b) #Exponentiation

array([[  4.48168907,   7.3890561 ,  20.08553692],
       [ 54.59815003, 148.4131591 , 403.42879349]])

In [44]:
np.sqrt(b) #Square root

array([[1.22474487, 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [47]:
np.sin(a) #Print sines of an array

array([0.84147098, 0.90929743, 0.14112001])

array([0.84147098, 0.90929743, 0.14112001])

In [48]:
np.cos(b) #Element-wise cosine

array([[ 0.0707372 , -0.41614684, -0.9899925 ],
       [-0.65364362,  0.28366219,  0.96017029]])

In [49]:
np.log(a) #Element-wise natural logarithm

array([0.        , 0.69314718, 1.09861229])

In [50]:
e.dot(f) #Dot product

array([[7., 7.],
       [7., 7.]])

### Comparison

In [51]:
a == b #Element-wise comparison

array([[False,  True,  True],
       [False, False, False]])

In [52]:
a < 2 #Element-wise comparison

array([ True, False, False])

In [54]:
print(a)

[1 2 3]


In [55]:
print(b)

[[1.5 2.  3. ]
 [4.  5.  6. ]]


In [56]:
x = [2,1,1]
a < x

array([ True, False, False])

In [57]:
np.array_equal(a, b) #Array-wise comparison

False

### Aggregate Functions


In [58]:
a.sum() #Array-wise sum

6

In [59]:
a.min() #Array-wise minimum value

1

In [60]:
b.max(axis=0) #Maximum value of an array row

array([4., 5., 6.])

In [61]:
print(b)

[[1.5 2.  3. ]
 [4.  5.  6. ]]


In [62]:
b.cumsum(axis=1) #Cumulative sum of the elements

array([[ 1.5,  3.5,  6.5],
       [ 4. ,  9. , 15. ]])

In [66]:
a

array([1, 2, 3])

In [63]:
a.mean() #Mean

2.0

In [67]:
np.median(b) #Median

3.5

In [76]:
 y = np.array ([20,21,20,22,23,20,19])
 print ('Sum', y.sum())
 print ('Count', y.size)
 print ('Mean', y.mean())
 print ('Median', np.median(y))

Sum 145
Count 7
Mean 20.714285714285715
Median 20.0


In [65]:
np.corrcoef(a) #Correlation coefficient

1.0

In [77]:
np.std(b) #Standard deviation

1.5920810978785667

In [78]:
np.std(y) #Standard deviation

1.2777531299998799

## Copying Arrays

In [79]:
h = a.view() #Create a view of the array with the same data

In [81]:
h

array([1, 2, 3])

In [82]:
np.copy(a) #Create a copy of the array

array([1, 2, 3])

In [83]:
k = a.copy() #Create a deep copy of the array
k

array([1, 2, 3])